#! /bin/sh

bspc monitor -d term web code media games extra

bspc config border_width         4
bspc config window_gap           5

# colors
background = #000000
foreground = #ffffff

bspc config normal_border_color "#$background"
bspc config focused_border_color "#$foreground"
bspc config presel_feedback_color "#$foreground"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Launch polybar
$HOME/.config/polybar/launch.sh
